### ISSUE TITLE
connection to AmazonMQ

### ISSUE THREAD

**Issue by hanman18** [manageplaces/Stompex#8] opened 2018-05-02 22:24 UTC
I've tried to connect to a an AmazonMQ broker but subscribing to a topic on said broker doesnt work. 
I've tried to connect to the broker and subscribe to a topic: 

```
{:ok, conn} = Stompex.connect("stomp+ssl://xxx.amazonaws.com",61614,"xxx","xxx")
        callback = fn(msg) ->
            IO.inspect msg
        end
        Stompex.register_callback(conn, "/topic/test_topic", callback)
        Stompex.subscribe(conn, "/topic/test_topic", %{"selector", "JMSType = \'test_type\' "})
```
Here is the error below:
``` [error] GenServer #PID<xxx> terminating
** (FunctionClauseError) no function clause matching in :gen_tcp.send/2
    (kernel) gen_tcp.erl:265: :gen_tcp.send(nil, [83, 85, 66, 83, 67, 82, 73, 66, 69, 10, 97, 99, 107, 58, 99, 108, 105, 101, 110, 116, 10, 100, 101, 115, 116, 105, 110, 97, 116, 105, 111, 110, 58, 47, 116, 111, 112, 105, 99, 47, 101, 118, 101, 110, 116, 47, 100, 100, 98, 95, ...])
    (stompex) lib/stompex.ex:258: Stompex.subscribe_to_destination/4
    (connection) lib/connection.ex:488: Connection.handle_call/3
    (stdlib) gen_server.erl:636: :gen_server.try_handle_call/4
    (stdlib) gen_server.erl:665: :gen_server.handle_msg/6
    (stdlib) proc_lib.erl:247: :proc_lib.init_p_do_apply/3
Last message (from #PID<xxxx>): {:subscribe, "/topic/test_topic”, %{"selector", "JMSType = \'test_type\' "}}
State: %{callbacks: %{"/topic/event/test_changes” => [#Function<xxxx/1 in Application/0>]}, calling_process: #PID<xxx>, headers: %{"accept-version" => "1.2", "login" => “xxxx”, "passcode" => “xxxx”}, host: "stomp+ssl://xxxxamazonaws.com", port: 61614, receiver: nil, send_to_caller: false, sock: nil, subscription_id: 0, subscriptions: %{}, timeout: 10000, version: 1.2}
Client #PID<xxxx> is alive
    (stdlib) gen.erl:169: :gen.do_call/4
    (elixir) lib/gen_server.ex:828: GenServer.call/3
    (application) Application.Function/2
    (phoenix) lib/phoenix/channel/server.ex:258: Phoenix.Channel.Server.handle_info/2
    (stdlib) gen_server.erl:616: :gen_server.try_dispatch/4
    (stdlib) gen_server.erl:686: :gen_server.handle_msg/6
    (stdlib) proc_lib.erl:247: :proc_lib.init_p_do_apply/3 
```
Any ideas on whether additional headers need to be added to be able to subscribe to a topic on AmazonMQ?

**Comment by shymega** [comment] 2018-05-02 23:30
Hi,

I'd like to see if removing the URI part will work: i.e, just the hostname.

IIRC, Stompex does not have SSL support yet (see #5), but it is on the roadmap.

Further to that, if you give the `ssl` branch a go, that'll help with further investigations.

Is the topic/queue you're subscribing to valid? Do other STOMP clients work with that?

Cheers.

On 2 May 2018 23:24:32 BST, hanman18 <notifications@github.com> wrote:
>I've tried to connect to a an AmazonMQ broker but subscribing to a
>topic on said broker doesnt work. 
>I've tried to connect to the broker and subscribe to a topic: 
>
>{:ok, conn} =
>Stompex.connect("stomp+ssl://xxx.amazonaws.com",61614,"xxx","xxx")
>        callback = fn(msg) ->
>            IO.inspect msg
>        end
>        Stompex.register_callback(conn, "/topic/test_topic", callback)
>Stompex.subscribe(conn, "/topic/test_topic", %{"selector", "JMSType =
>\'test_type\' "})
>
>Here is the error below:
>[error] GenServer #PID<xxx> terminating
>** (FunctionClauseError) no function clause matching in :gen_tcp.send/2
>(kernel) gen_tcp.erl:265: :gen_tcp.send(nil, [83, 85, 66, 83, 67, 82,
>73, 66, 69, 10, 97, 99, 107, 58, 99, 108, 105, 101, 110, 116, 10, 100,
>101, 115, 116, 105, 110, 97, 116, 105, 111, 110, 58, 47, 116, 111, 112,
>105, 99, 47, 101, 118, 101, 110, 116, 47, 100, 100, 98, 95, ...])
>    (stompex) lib/stompex.ex:258: Stompex.subscribe_to_destination/4
>    (connection) lib/connection.ex:488: Connection.handle_call/3
>    (stdlib) gen_server.erl:636: :gen_server.try_handle_call/4
>    (stdlib) gen_server.erl:665: :gen_server.handle_msg/6
>    (stdlib) proc_lib.erl:247: :proc_lib.init_p_do_apply/3
>Last message (from #PID<xxxx>): {:subscribe, "/topic/test_topic”,
>%{"selector", "JMSType = \'test_type\' "}}
>State: %{callbacks: %{"/topic/event/test_changes” => [#Function<xxxx/1
>in Application/0>]}, calling_process: #PID<xxx>, headers:
>%{"accept-version" => "1.2", "login" => “xxxx”, "passcode" => “xxxx”},
>host: "stomp+ssl://xxxxamazonaws.com", port: 61614, receiver: nil,
>send_to_caller: false, sock: nil, subscription_id: 0, subscriptions:
>%{}, timeout: 10000, version: 1.2}
>Client #PID<xxxx> is alive
>    (stdlib) gen.erl:169: :gen.do_call/4
>    (elixir) lib/gen_server.ex:828: GenServer.call/3
>    (application) Application.Function/2
>(phoenix) lib/phoenix/channel/server.ex:258:
>Phoenix.Channel.Server.handle_info/2
>    (stdlib) gen_server.erl:616: :gen_server.try_dispatch/4
>    (stdlib) gen_server.erl:686: :gen_server.handle_msg/6
>    (stdlib) proc_lib.erl:247: :proc_lib.init_p_do_apply/3
>
>Any ideas on whether additional headers need to be added to be able to
>subscribe to a topic on AmazonMQ?
>
>-- 
>You are receiving this because you are subscribed to this thread.
>Reply to this email directly or view it on GitHub:
>https://github.com/manageplaces/Stompex/issues/8

-- 
Sent from my Android device with K-9 Mail. Please excuse my brevity.

**Comment by pareeohnos** [comment] 2018-05-03 09:21
The `ssl` branch has support for SSL connections so it might be worth trying that, but the issue appears to be the connection itself is potentially failing. It seems that by the time it gets to calling the `send` function of `:gen_tcp`, the connection is `nil` which obviously it shouldn't be.

It's possible that because SSL isn't being used, that amazon is immediately rejecting the connection but I can't say for sure.

Please try the SSL branch and report back as this may resolve the issues

**Comment by shymega** [comment] 2018-05-03 14:10
@pareeohnos I think you got the better end of the stick than me there! I had a late night, so I wasn't thinking straight. Just gonna comment on the SSL branch to remind myself to add SSL support to the Erlang lib..

I've also edited my original comment.

**Comment by shymega** [comment] 2018-05-03 14:13
Additionally: @hanman18 Could you wrap the outputs from Stompex in a Markdown code block?

Use ``` at the beginning and the end to wrap them in a code block. Cheers, that'll make it easier to read :)

**Comment by hanman18** [comment] 2018-05-03 14:43
Hi @shymega @pareeohnos I've tried the SSL branch and get the same error.

**Comment by pareeohnos** [comment] 2018-05-03 14:53
@hanman18  hm alright. Not sure if it's related, but you do appear to have a syntax error. Your call to `subscribe` has an invalid final argument

    %{"selector", "JMSType = 'test_type' "}

This should be

    %{"selector" => "JMSType = 'test_type' "}

Out of curiosity, what happens if you omit this header entirely? Wondering if it's causing the frame handling to fail due to an invalid format

**Comment by hanman18** [comment] 2018-05-03 15:07
Hi @pareeohnos I've tried it without adding any of the selectors like below
``` Stompex.subscribe(conn, "/topic/test_topic") ```

Another thing to add is that Stompex.connect responds successfully. I receive the error once I subscribe to a topic

**Comment by shymega** [comment] 2018-05-03 15:11
> I receive the error once I subscribe to a topic

Yeah, I did think that was the case from the backtrace.. do Amazon's STOMP service offer any logs at all?

**Comment by pareeohnos** [comment] 2018-05-03 17:50
@hanman18 I realise the issue is appearing when you try to subscribe, but the error is indicating that when you request that subscription, that the connection no longer exists, so somewhere between connecting and subscribing, something is happening.

It's possible that whilst the `conn` is being returned correctly initially, that amazon are terminating the connection for some reason. As @shymega suggests, check if there are any logs on Amazon that you can inspect. Also try inspecting what the value of `conn` is just before the call to `subscribe` and making sure it's still alive.

**Comment by shymega** [comment] 2018-05-03 17:55
Oh, of course. I didn't read the backlog fully. Good catch @pareeohnos.

**Comment by hanman18** [comment] 2018-05-04 14:07
Hi @pareeohnos @shymega is there to add set timeoiut into the connection headers?

**Comment by hanman18** [comment] 2018-05-04 15:45
Hi @pareeohnos  @shymega I've also tried testing in the elixir interactive shell and it looks like it connects and closes the connection right away: 

```
Stompex.connect("b-xxx.amazonaws.com",61614,"xxx","xxx")
{:ok, #PID<0.335.0>}
iex(2)> [warn] Ignoring `set_command/2` call. Command '^U^C^C^@^B^B' is invalid
** (EXIT from #PID<0.333.0>) shell process exited with reason: an exception was raised:
    ** (MatchError) no match of right hand side value: {:error, :closed}
        (stompex) lib/stompex/receiver/receiver.ex:52: Stompex.Receiver.read_headers/3
        (stompex) lib/stompex/receiver/receiver.ex:34: Stompex.Receiver.do_receive/1
        (stompex) lib/stompex/receiver/receiver.ex:26: Stompex.Receiver.handle_call/3
        (stdlib) gen_server.erl:636: :gen_server.try_handle_call/4
        (stdlib) gen_server.erl:665: :gen_server.handle_msg/6
        (stdlib) proc_lib.erl:247: :proc_lib.init_p_do_apply/3
```

**Comment by shymega** [comment] 2018-05-04 18:16
@hanman18 Thanks for wrapping your output in code blocks. Could you do it for the first code output in your initial issue? Thanks.

With regards to the error you're receiving now: it looks like Amazon's IoT implementation is sending either unexpected chars, and/or closing the TCP connection unexpectedly.

Have you managed to get any debug logs from Amazon?

The timeout you describe is known as a heartbeat in STOMP, and if I recall correctly, customising heartbeats is something I'm working on, that is, to the STOMP server, but generally reading heartbeats is done automatically by the client; the limitation is in essence changing the frequency of the [heartbeats](hbeat)

[hbeat]: https://stomp.github.io/stomp-specification-1.1.html#Heart-beating

**Comment by pareeohnos** [comment] 2018-05-05 08:15
Yeah that looks like amazon are sending a completely invalid response. Is it definitely configured to run with STOMP? I’ve never used AmazonMQ but do you need to do more than just set STOMP in the URL?

But based on that error the issues is almost definitely amazon returning an invalid response. Or if not a response, then just a random message and I’m unsure why. It’s possible they’re sending heartbeats that are not just empty frames. As a test, set the heartbeat header when you connect to specify you don’t want to receive heartbeats. Stomped currently expects a blank frame with just a new line character as a heartbeat, so if they are doing something different then it will cause Stompex to fail. 

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Closed as completed** 2019-02-14 16:34 UTC
